/**
 * Human-readable display names for Arborium language identifiers.
 * Keys mirror the entries in `ALL_LANGUAGES` (see `rehype.ts`).
 */
export const LANGUAGE_LABELS: Record<string, string> = {
  ada: "Ada",
  agda: "Agda",
  asciidoc: "AsciiDoc",
  asciidoc_inline: "AsciiDoc Inline",
  asm: "Assembly",
  awk: "AWK",
  bash: "Bash",
  batch: "Batch",
  c: "C",
  "c-sharp": "C#",
  caddy: "Caddyfile",
  capnp: "Cap'n Proto",
  cedar: "Cedar",
  cedarschema: "Cedar Schema",
  clojure: "Clojure",
  cmake: "CMake",
  cobol: "COBOL",
  commonlisp: "Common Lisp",
  cpp: "C++",
  css: "CSS",
  d: "D",
  dart: "Dart",
  devicetree: "Device Tree",
  diff: "Diff",
  dockerfile: "Dockerfile",
  dot: "DOT",
  elisp: "Emacs Lisp",
  elixir: "Elixir",
  elm: "Elm",
  erlang: "Erlang",
  fish: "Fish",
  fsharp: "F#",
  gitattributes: "Git Attributes",
  gleam: "Gleam",
  glsl: "GLSL",
  go: "Go",
  graphql: "GraphQL",
  groovy: "Groovy",
  haskell: "Haskell",
  hcl: "HCL",
  hlsl: "HLSL",
  html: "HTML",
  idris: "Idris",
  ini: "INI",
  java: "Java",
  javascript: "JavaScript",
  jinja2: "Jinja2",
  jq: "jq",
  jsdoc: "JSDoc",
  json: "JSON",
  julia: "Julia",
  just: "Just",
  kconfig: "Kconfig",
  kdl: "KDL",
  kotlin: "Kotlin",
  lean: "Lean",
  lua: "Lua",
  make: "Makefile",
  markdown: "Markdown",
  matlab: "MATLAB",
  meson: "Meson",
  nginx: "nginx",
  ninja: "Ninja",
  nix: "Nix",
  objc: "Objective-C",
  ocaml: "OCaml",
  odin: "Odin",
  perl: "Perl",
  php: "PHP",
  postscript: "PostScript",
  powershell: "PowerShell",
  prolog: "Prolog",
  proto: "Protocol Buffers",
  python: "Python",
  query: "Tree-sitter Query",
  r: "R",
  regex: "Regex",
  rego: "Rego",
  rescript: "ReScript",
  ron: "RON",
  ruby: "Ruby",
  rust: "Rust",
  scala: "Scala",
  scheme: "Scheme",
  scss: "SCSS",
  solidity: "Solidity",
  sparql: "SPARQL",
  sql: "SQL",
  "ssh-config": "SSH Config",
  starlark: "Starlark",
  styx: "Styx",
  svelte: "Svelte",
  swift: "Swift",
  textproto: "Text Proto",
  thrift: "Thrift",
  tlaplus: "TLA+",
  toml: "TOML",
  tsx: "TSX",
  typescript: "TypeScript",
  typst: "Typst",
  uiua: "Uiua",
  vb: "Visual Basic",
  verilog: "Verilog",
  vhdl: "VHDL",
  vim: "Vim",
  vue: "Vue",
  wit: "WIT",
  x86asm: "x86 Assembly",
  xml: "XML",
  yaml: "YAML",
  yuri: "Yuri",
  zig: "Zig",
  zsh: "Zsh",
}

/**
 * Return a human-readable label for an Arborium language identifier.
 * Falls back to the raw identifier when no display name is registered.
 */
export function getLanguageLabel(language: string): string {
  return LANGUAGE_LABELS[language] ?? language
}
